name: WalletMonitor
description: Cross-chain portfolio monitoring

networks:
  - id: 1
    start_block: 18500000
  - id: 137
    start_block: 48000000
  - id: 42161
    start_block: 140000000

contracts:
  - name: USDC_Ethereum
    abi_file_path: ./abis/erc20.json
    address: 
      - address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    handler: ./src/handlers.ts
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: USDC_Polygon
    abi_file_path: ./abis/erc20.json
    address:
      - address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    handler: ./src/handlers.ts
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: USDC_Arbitrum
    abi_file_path: ./abis/erc20.json
    address:
      - address: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8"
    handler: ./src/handlers.ts
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 value)